# Generated by Django 5.2.11 on 2026-03-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
