# Generated by Django 5.2.11 on 2026-03-04 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='vote_requires_user_or_session',
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('guest_session_id__isnull', True), ('voter__isnull', False)), models.Q(('guest_session_id__isnull', False), ('voter__isnull', True)), _connector='OR'), models.Q(('guest_session_id', ''), _negated=True)), name='vote_requires_user_or_session'),
        ),
    ]
