# Generated by Django 5.2.11 on 2026-03-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vote_vote_requires_user_or_session_game_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='category',
            field=models.CharField(blank=True, choices=[('truth', 'Truth'), ('dare', 'Dare')], max_length=20, null=True),
        ),
    ]
