# Generated by Django 5.2.11 on 2026-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vote_vote_requires_user_or_session_game_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
