# Generated by Django 5.2.11 on 2026-03-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prompt_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='category',
        ),
    ]
