# Generated by Django 5.2.11 on 2026-03-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prompt_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='upvotes',
        ),
    ]
