# Generated by Django 5.2.11 on 2026-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_prompt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='category',
            field=models.CharField(blank=True, choices=[('truth', 'Truth'), ('dare', 'Dare')], max_length=20, null=True),
        ),
    ]
